# Generated by Django 2.1a1 on 2018-08-18 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=50)),
                ('incantation', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('reference', models.TextField()),
                ('extract', models.TextField()),
                ('extract_author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
