# Generated by Django 2.1a1 on 2018-08-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='contributor',
        ),
    ]
