# Generated by Django 2.1a1 on 2018-08-18 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spells', '0002_remove_spell_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='contributor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
