# Generated by Django 2.1a1 on 2018-08-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_spell_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(),
        ),
    ]
